### ISSUE TITLE
How to deal with formValueSelector and connect and when you are pre populating redux form

### ISSUE THREAD

**Issue by kailashvele** [frodare/redux-forms-unsaved-changes-prompt#1]

**Comment by frodare** [comment]
You should be able to use `connect`, `formValueSelector` and `initialValues` like normal.  The only thing you should need to add to get this to work is to wrap your form with the `unsavedPrompt(formName, 'message')`  HOC like on this line:

https://github.com/frodare/redux-forms-unsaved-changes-prompt/blob/master/src/ContactForm.js#L31

**Comment by kailashvele** [comment]
I tried that but was not successful. Currently exploring the same.
Can you write a small example? that will get the doubt clear. As I am not familiar with the composition and functional programming. Thank You.

**Comment by frodare** [comment]
I will try to create an example tomorrow.

**Comment by frodare** [comment]
I have updated the code to show how connect, initialValues and the formValueSelector can be used, I hope it helps,

https://github.com/frodare/redux-forms-unsaved-changes-prompt/commit/6fc4ab89f84e5b6c3a5e62608a689aab562ad26d
